services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.test
  node:
    container_name: node
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env.test